"""
Management command that creates a demo user with realistic sample
companies, job applications and interviews so the app can be explored
immediately after setup.

Usage:
    python manage.py load_sample_data
"""

import random
from datetime import date, time, timedelta

from django.core.management.base import BaseCommand
from django.db import transaction

from accounts.models import User
from applications.models import JobApplication
from companies.models import Company
from interviews.models import Interview

DEMO_EMAIL = "demo@jobtrack.dev"
DEMO_PASSWORD = "DemoPass123"

SAMPLE_COMPANIES = [
    {"company_name": "TCS", "website": "https://www.tcs.com", "location": "Mumbai, India", "industry": "IT Services"},
    {"company_name": "Infosys", "website": "https://www.infosys.com", "location": "Bengaluru, India", "industry": "IT Services"},
    {"company_name": "Wipro", "website": "https://www.wipro.com", "location": "Bengaluru, India", "industry": "IT Services"},
    {"company_name": "Accenture", "website": "https://www.accenture.com", "location": "Hyderabad, India", "industry": "Consulting"},
    {"company_name": "Microsoft", "website": "https://www.microsoft.com", "location": "Redmond, WA", "industry": "Technology"},
    {"company_name": "Amazon", "website": "https://www.amazon.com", "location": "Seattle, WA", "industry": "E-commerce / Cloud"},
    {"company_name": "Google", "website": "https://www.google.com", "location": "Mountain View, CA", "industry": "Technology"},
    {"company_name": "Deloitte", "website": "https://www.deloitte.com", "location": "New York, NY", "industry": "Consulting"},
]

JOB_TITLES = [
    "Software Developer Intern", "Junior Software Engineer", "Backend Developer",
    "Frontend Developer", "Full Stack Developer", "Associate Software Engineer",
    "Python Developer", "QA Engineer",
]

STATUSES = [c[0] for c in JobApplication.Status.choices]
JOB_TYPES = [c[0] for c in JobApplication.JobType.choices]
PRIORITIES = [c[0] for c in JobApplication.Priority.choices]


class Command(BaseCommand):
    help = "Creates a demo user with sample companies, job applications and interviews."

    def add_arguments(self, parser):
        parser.add_argument(
            "--reset",
            action="store_true",
            help="Delete existing demo data (demo@jobtrack.dev) before recreating it.",
        )

    @transaction.atomic
    def handle(self, *args, **options):
        if options["reset"]:
            User.objects.filter(email=DEMO_EMAIL).delete()
            self.stdout.write(self.style.WARNING("Existing demo user removed."))

        user, created = User.objects.get_or_create(
            email=DEMO_EMAIL,
            defaults={"full_name": "Demo User"},
        )
        if created:
            user.set_password(DEMO_PASSWORD)
            user.save()
            self.stdout.write(self.style.SUCCESS(f"Created demo user: {DEMO_EMAIL} / {DEMO_PASSWORD}"))
        else:
            self.stdout.write("Demo user already exists, reusing it.")

        companies = []
        for data in SAMPLE_COMPANIES:
            company, _ = Company.objects.get_or_create(
                company_name=data["company_name"], defaults=data
            )
            companies.append(company)

        if JobApplication.objects.filter(user=user).exists():
            self.stdout.write("Demo user already has applications - skipping sample application creation.")
            self.stdout.write(self.style.SUCCESS("Done. (Use --reset to regenerate everything.)"))
            return

        today = date.today()
        created_apps = []
        for i in range(18):
            company = random.choice(companies)
            status = random.choice(STATUSES)
            app_date = today - timedelta(days=random.randint(1, 150))
            application = JobApplication.objects.create(
                user=user,
                company=company,
                job_title=random.choice(JOB_TITLES),
                job_type=random.choice(JOB_TYPES),
                location=company.location,
                salary=random.choice([None, 400000, 600000, 850000, 1200000]),
                job_url=f"{company.website}/careers/job-{i+1}",
                application_date=app_date,
                status=status,
                priority=random.choice(PRIORITIES),
                notes="Sample/demo application generated by load_sample_data.",
            )
            created_apps.append(application)

        # Add interviews for applications that have progressed past "Applied".
        interview_types = [c[0] for c in Interview.InterviewType.choices]
        for application in created_apps:
            if application.status in ("Interview", "Selected", "Rejected"):
                num_rounds = random.randint(1, 2)
                for r in range(num_rounds):
                    interview_date = application.application_date + timedelta(days=7 * (r + 1))
                    result = "Pending"
                    if interview_date < today:
                        result = random.choice(["Passed", "Failed", "Pending"])
                    Interview.objects.create(
                        application=application,
                        interview_date=interview_date,
                        interview_time=time(hour=random.choice([10, 11, 14, 15, 16])),
                        interview_type=random.choice(interview_types),
                        interviewer="Sample Interviewer",
                        meeting_link="https://meet.google.com/sample-demo-link",
                        notes="Sample/demo interview generated by load_sample_data.",
                        result=result,
                    )

        # A few guaranteed upcoming interviews so the dashboard widget has data.
        upcoming_app = random.choice(created_apps)
        for days_ahead in (2, 5):
            Interview.objects.create(
                application=upcoming_app,
                interview_date=today + timedelta(days=days_ahead),
                interview_time=time(hour=11),
                interview_type="Video",
                interviewer="Sample Hiring Manager",
                meeting_link="https://meet.google.com/sample-upcoming",
                notes="Sample/demo upcoming interview.",
                result="Pending",
            )

        self.stdout.write(self.style.SUCCESS(
            f"Sample data loaded: {len(companies)} companies, "
            f"{len(created_apps)} applications, and related interviews."
        ))
        self.stdout.write(self.style.SUCCESS(f"Login with: {DEMO_EMAIL} / {DEMO_PASSWORD}"))
