# Generated by Django 5.0.6 on 2026-09-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interview_date', models.DateField()),
                ('interview_time', models.TimeField()),
                ('interview_type', models.CharField(choices=[('Phone', 'Phone'), ('Video', 'Video'), ('Technical', 'Technical'), ('HR', 'HR'), ('Onsite', 'Onsite')], default='Video', max_length=20)),
                ('interviewer', models.CharField(blank=True, max_length=150)),
                ('meeting_link', models.URLField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('result', models.CharField(choices=[('Pending', 'Pending'), ('Passed', 'Passed'), ('Failed', 'Failed')], default='Pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interviews', to='applications.jobapplication')),
            ],
            options={
                'ordering': ['interview_date', 'interview_time'],
                'indexes': [models.Index(fields=['interview_date'], name='interviews__intervi_fd9caf_idx')],
            },
        ),
    ]
